package com.qipai.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdmin<M extends BaseAdmin<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAdminName(java.lang.String adminName) {
		set("admin_name", adminName);
	}

	public java.lang.String getAdminName() {
		return get("admin_name");
	}

	public void setAdminPwd(java.lang.String adminPwd) {
		set("admin_pwd", adminPwd);
	}

	public java.lang.String getAdminPwd() {
		return get("admin_pwd");
	}

	public void setLoginTime(java.util.Date loginTime) {
		set("login_time", loginTime);
	}

	public java.util.Date getLoginTime() {
		return get("login_time");
	}

	public void setLogoutTime(java.util.Date logoutTime) {
		set("logout_time", logoutTime);
	}

	public java.util.Date getLogoutTime() {
		return get("logout_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setAdminIp(java.lang.String adminIp) {
		set("admin_ip", adminIp);
	}

	public java.lang.String getAdminIp() {
		return get("admin_ip");
	}

}
