package com.qipai.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseScore<M extends BaseScore<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setGameId(java.lang.Integer gameId) {
		set("game_id", gameId);
	}

	public java.lang.Integer getGameId() {
		return get("game_id");
	}

	public void setGameTime(java.util.Date gameTime) {
		set("game_time", gameTime);
	}

	public java.util.Date getGameTime() {
		return get("game_time");
	}

	public void setPayMoney(java.lang.Integer payMoney) {
		set("pay_money", payMoney);
	}

	public java.lang.Integer getPayMoney() {
		return get("pay_money");
	}

	public void setAwardMoney(java.lang.Integer awardMoney) {
		set("award_money", awardMoney);
	}

	public java.lang.Integer getAwardMoney() {
		return get("award_money");
	}

}
