package com.qipai.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLabaconf<M extends BaseLabaconf<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAxis(java.lang.Integer axis) {
		set("axis", axis);
	}

	public java.lang.Integer getAxis() {
		return get("axis");
	}

	public void setCards(java.lang.String cards) {
		set("cards", cards);
	}

	public java.lang.String getCards() {
		return get("cards");
	}

	public void setGameId(java.lang.Integer gameId) {
		set("game_id", gameId);
	}

	public java.lang.Integer getGameId() {
		return get("game_id");
	}

}
