package com.qipai.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReward<M extends BaseReward<M>> extends Model<M> implements IBean {

	public void setRewardId(java.lang.Integer rewardId) {
		set("reward_id", rewardId);
	}

	public java.lang.Integer getRewardId() {
		return get("reward_id");
	}

	public void setRewardDesc(java.lang.String rewardDesc) {
		set("reward_desc", rewardDesc);
	}

	public java.lang.String getRewardDesc() {
		return get("reward_desc");
	}

	public void setMoney(java.lang.Long money) {
		set("money", money);
	}

	public java.lang.Long getMoney() {
		return get("money");
	}

	public void setTimes(java.lang.Integer times) {
		set("times", times);
	}

	public java.lang.Integer getTimes() {
		return get("times");
	}

	public void setScore(java.lang.Long score) {
		set("score", score);
	}

	public java.lang.Long getScore() {
		return get("score");
	}

}
