package com.qipai.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGamePrize<M extends BaseGamePrize<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setPrize(java.lang.Integer prize) {
		set("prize", prize);
	}

	public java.lang.Integer getPrize() {
		return get("prize");
	}

}
