package com.qipai.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCharge<M extends BaseCharge<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setMoney(java.lang.Integer money) {
		set("money", money);
	}

	public java.lang.Integer getMoney() {
		return get("money");
	}

	public void setCoin(java.lang.Integer coin) {
		set("coin", coin);
	}

	public java.lang.Integer getCoin() {
		return get("coin");
	}

	public void setTxnTime(java.util.Date txnTime) {
		set("txn_time", txnTime);
	}

	public java.util.Date getTxnTime() {
		return get("txn_time");
	}

	public void setFrom(java.lang.String from) {
		set("from", from);
	}

	public java.lang.String getFrom() {
		return get("from");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
	}

	public java.lang.String getOrderNo() {
		return get("order_no");
	}

	public void setOrdreState(java.lang.String ordreState) {
		set("ordre_state", ordreState);
	}

	public java.lang.String getOrdreState() {
		return get("ordre_state");
	}

}
