package com.qipai.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTax<M extends BaseTax<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTax(java.lang.Integer tax) {
		set("tax", tax);
	}

	public java.lang.Integer getTax() {
		return get("tax");
	}

	public void setGameId(java.lang.Integer gameId) {
		set("game_id", gameId);
	}

	public java.lang.Integer getGameId() {
		return get("game_id");
	}

	public void setStock(java.lang.Integer stock) {
		set("stock", stock);
	}

	public java.lang.Integer getStock() {
		return get("stock");
	}

	public void setActivMoney(java.lang.Integer activMoney) {
		set("activ_money", activMoney);
	}

	public java.lang.Integer getActivMoney() {
		return get("activ_money");
	}

	public void setCoinPoo(java.lang.Integer coinPoo) {
		set("coin_poo", coinPoo);
	}

	public java.lang.Integer getCoinPoo() {
		return get("coin_poo");
	}

}
