package com.qipai.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public void setPwd(java.lang.String pwd) {
		set("pwd", pwd);
	}

	public java.lang.String getPwd() {
		return get("pwd");
	}

	public void setPwd2(java.lang.String pwd2) {
		set("pwd2", pwd2);
	}

	public java.lang.String getPwd2() {
		return get("pwd2");
	}

	public void setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
	}

	public java.lang.String getNickName() {
		return get("nick_name");
	}

	public void setCoin(java.lang.Integer coin) {
		set("coin", coin);
	}

	public java.lang.Integer getCoin() {
		return get("coin");
	}

	public void setBankCoin(java.lang.Integer bankCoin) {
		set("bank_coin", bankCoin);
	}

	public java.lang.Integer getBankCoin() {
		return get("bank_coin");
	}

	public void setLoginTime(java.util.Date loginTime) {
		set("login_time", loginTime);
	}

	public java.util.Date getLoginTime() {
		return get("login_time");
	}

	public void setLogoutTime(java.util.Date logoutTime) {
		set("logout_time", logoutTime);
	}

	public java.util.Date getLogoutTime() {
		return get("logout_time");
	}

	public void setIsVip(java.lang.String isVip) {
		set("is_vip", isVip);
	}

	public java.lang.String getIsVip() {
		return get("is_vip");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}

	public java.lang.String getComment() {
		return get("comment");
	}

	public void setOnline(java.lang.String online) {
		set("online", online);
	}

	public java.lang.String getOnline() {
		return get("online");
	}

}
