package com.qipai.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDesk<M extends BaseDesk<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDeskName(java.lang.String deskName) {
		set("desk_name", deskName);
	}

	public java.lang.String getDeskName() {
		return get("desk_name");
	}

	public void setRoomId(java.lang.Integer roomId) {
		set("room_id", roomId);
	}

	public java.lang.Integer getRoomId() {
		return get("room_id");
	}

	public void setDeskStatus(java.lang.Integer deskStatus) {
		set("desk_status", deskStatus);
	}

	public java.lang.Integer getDeskStatus() {
		return get("desk_status");
	}

	public void setGameId(java.lang.Integer gameId) {
		set("game_id", gameId);
	}

	public java.lang.Integer getGameId() {
		return get("game_id");
	}

	public void setIsVipRoom(java.lang.Boolean isVipRoom) {
		set("is_vip_room", isVipRoom);
	}

	public java.lang.Boolean getIsVipRoom() {
		return get("is_vip_room");
	}

	public void setMaxPlayer(java.lang.Integer maxPlayer) {
		set("max_player", maxPlayer);
	}

	public java.lang.Integer getMaxPlayer() {
		return get("max_player");
	}

	public void setMinPlayer(java.lang.Integer minPlayer) {
		set("min_player", minPlayer);
	}

	public java.lang.Integer getMinPlayer() {
		return get("min_player");
	}

	public void setGameTime(java.util.Date gameTime) {
		set("game_time", gameTime);
	}

	public java.util.Date getGameTime() {
		return get("game_time");
	}

}
