package com.qipai.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("admin", "id", Admin.class);
		arp.addMapping("charge", "id", Charge.class);
		arp.addMapping("desk", "id", Desk.class);
		arp.addMapping("game", "id", Game.class);
		arp.addMapping("labaconf", "id", Labaconf.class);
		arp.addMapping("notice", "id", Notice.class);
		arp.addMapping("rank", "id", Rank.class);
		arp.addMapping("reward", "reward_id", Reward.class);
		arp.addMapping("room", "id", Room.class);
		arp.addMapping("score", "id", Score.class);
		arp.addMapping("sysconf", "id", Sysconf.class);
		arp.addMapping("tax", "id", Tax.class);
		arp.addMapping("user", "id", User.class);
	}
}

