package com.qipai.common.model;

import com.qipai.common.model.base.BaseCharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Charge extends BaseCharge<Charge> {
	public static final Charge dao = new Charge();
}
