package com.qipai.common.model;

import com.qipai.common.model.base.BaseDesk;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Desk extends BaseDesk<Desk> {
	public static final Desk dao = new Desk();
}
