package com.qipai.common.model;

import com.qipai.common.model.base.BaseGamePrize;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GamePrize extends BaseGamePrize<GamePrize> {
	public static final GamePrize dao = new GamePrize();
}
