package com.qipai.common.model;

import com.qipai.common.model.base.BaseLabaconf;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Labaconf extends BaseLabaconf<Labaconf> {
	public static final Labaconf dao = new Labaconf();
}
