package com.qipai.common.model;

import com.qipai.common.model.base.BaseNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Notice extends BaseNotice<Notice> {
	public static final Notice dao = new Notice();
}
