package com.qipai.common.model;

import com.qipai.common.model.base.BaseRank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rank extends BaseRank<Rank> {
	public static final Rank dao = new Rank();
}
