package com.qipai.common.model;

import com.qipai.common.model.base.BaseReward;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reward extends BaseReward<Reward> {
	public static final Reward dao = new Reward();
}
