package com.qipai.common.model;

import com.qipai.common.model.base.BaseScore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Score extends BaseScore<Score> {
	public static final Score dao = new Score();
}
