package com.qipai.common.model;

import java.util.concurrent.atomic.AtomicInteger;

import com.qipai.common.model.base.BaseTax;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tax extends BaseTax<Tax> {
	public static final Tax dao = new Tax();
	
	private AtomicInteger taxCoin = new AtomicInteger(0);
	private AtomicInteger taxStock = new AtomicInteger(0);
	
	public void addTax(int coin){
		taxCoin.addAndGet(coin);
	}
	
	public int getTaxCoin(){
		return taxCoin.get();
	}
	public Tax setTaxCoin(int coin){
		taxCoin.set(coin);
		return this;
	}
	
	public void addTaxStock(int coin){
		taxStock.addAndGet(coin);
	}

	public void updateCoinPoo() {
		this.setCoinPoo(this.getTaxCoin());
		this.setStock(taxStock.get());
		update();
	}
	
}
