package com.qipai.common.model;

import com.qipai.common.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
	
	public void addCoin(int coin){
		this.setCoin(getCoin()+coin);
	}
	
}
